export const exercisesList = [
    "Squat",
    "Flat Bench Press",
    "Incline Bench Press",
    "Overhead Press",
    "Bench Press",
    "Flat Barbell Bench Press",
    "Incline Barbell Bench Press",
    "Flat Dumbbell Press",
    "Incline Dumbbell Press",
    "Chest Fly Machine",
    "Cable Chest Fly",
    "Push-up",
    "Pull-up",
    "Chin-up",
    "Barbell Row",
    "Dumbbell Row",
    "Lat Pulldown",
    "Seated Cable Row",
    "Deadlift",
    "Dumbbell Hammer Curl",
    "Overhead Barbell Press",
    "Overhead Dumbbell Press",
    "Lateral Raise",
    "Front Raise",
    "Rear Delt Fly",
    "Cable Lateral Raise",
    "Face Pull",
    "Barbell Curl",
    "Dumbbell Curl",
    "Hammer Curl",
    "Preacher Curl",
    "Cable Curl",
    "Concentration Curl",
    "Close-grip Bench Press",
    "Skull Crushers",
    "Overhead Tricep Extension",
    "Seated Dumbbell Press",
    "Tricep Pushdown",
    "Dips",
    "Barbell Squat",
    "Front Squat",
    "Romanian Deadlift",
    "Walking Lunge",
    "Leg Press",
    "Leg Extension",
    "Leg Curl",
    "Bulgarian Split Squat",
    "Calf Raise",
    "Plank",
    "Cable Crunch",
    "Hanging Leg Raise",
    "Russian Twist",
    "Decline Sit-up",
    "Seated Row",
  ];